name: twutter
description: An example fullstack microblogging app in Flutter.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shorebird:
    git:
      url: https://github.com/shorebirdtech/shorebird.git
      path: packages/shorebird
  # shorebird_flutter:
  #   git:
  #     url: https://github.com/shorebirdtech/shorebird.git
  #     path: packages/shorebird_flutter
  meta: ^1.8.0
  # Remove these:
  json_annotation: ^4.7.0
  http: ^0.13.5
  shelf: ^1.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  # Remove these:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

# FIXME: Remove this dependency override.
# shorebird should always be a path dependency, but we would need to update
# the way docker files pull the shorebird packages for that to work.
# dependency_overrides:
#   shorebird:
#     path: ../shorebird/packages/shorebird
#   shorebird_flutter:
#     path: ../shorebird/packages/shorebird_flutter

flutter:
  uses-material-design: true
